name: Build .NET SDK

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'dotnet VMR branch name'
        required: true
        type: string
        default: main-9.x-loong

jobs:
  run:
    runs-on: ubuntu-latest

    steps:

    - name: Maximize build space
      uses: AdityaGarg8/remove-unwanted-software@v4.1
      with:
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-cached-tools: 'true'        

    - name: Clone repository
      run: |
        git clone --depth 1 -b ${{ inputs.branch }} https://github.com/driver1998/dotnet-nolsx

    - name: Build
      run: |
        docker run --platform linux/amd64 --rm -v${{ github.workspace }}/dotnet-nolsx:/dotnet -w /dotnet -e ROOTFS_DIR=/crossrootfs/loongarch64 \
          mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-net10.0-cross-loongarch64 \
          sh -c '
            ./prep-source-build.sh &&
            ./build.sh -sb --clean-while-building /p:TargetOS=linux /p:TargetArchitecture=loongarch64 /p:Crossbuild=true
          '

    - name: List assets directory
      run: |
        find "${{ github.workspace }}/dotnet/artifacts"

    - name: Upload .NET
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-sdk-linux-riscv64
        path: |
          ${{ github.workspace }}/dotnet/artifacts/assets/Release/Sdk/*/dotnet-sdk-*
          ${{ github.workspace }}/dotnet/artifacts/packages/Release/Shipping/runtime/Microsoft.NETCore.App.Crossgen2.linux-loongarch64.*.nupkg
